Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Next:
  Enabled: false
